import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <nav style={{ display: 'flex', gap: 24, padding: 16, borderBottom: '1px solid #eee', marginBottom: 24 }}>
          <Link href="/">Trang chủ</Link>
          <Link href="/gallery">Bộ sưu tập</Link>
          <Link href="/services">Dịch vụ</Link>
          <Link href="/contact">Liên hệ</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
